apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai-api
  labels:
    app: crawl4ai
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawl4ai
      component: api
  template:
    metadata:
      labels:
        app: crawl4ai
        component: api
    spec:
      containers:
      - name: api
        image: ${DOCKER_REPO}/crawl4ai:latest  # Replace with your Docker image
        command: ["python", "api_server.py"]
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SCRAPINGBEE_API_KEY
          valueFrom:
            secretKeyRef:
              name: crawl4ai-secrets
              key: scrapingbee-api-key
        - name: REDIS_HOST
          value: "crawl4ai-redis"
        - name: API_MODE
          value: "true"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: crawl4ai-api
spec:
  selector:
    app: crawl4ai
    component: api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
