apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl4ai-redis
  labels:
    app: crawl4ai
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawl4ai
      component: redis
  template:
    metadata:
      labels:
        app: crawl4ai
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: crawl4ai-redis
spec:
  selector:
    app: crawl4ai
    component: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
