name: Deploy Crawl4AI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crawl4ai:latest
          platforms: linux/amd64  # For Digital Ocean compatibility

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: 164.92.69.88
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crawl4ai:latest
            
            # Stop the current container
            docker stop crawl4ai-container || true
            docker rm crawl4ai-container || true
            
            # Run the new container with the same configuration
            docker run -d -p 80:8000 \
              -e "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
              -e "SECURITY_ENABLED=true" \
              -e "JWT_ENABLED=true" \
              -e "SCRAPINGBEE_KEY=${{ secrets.SCRAPINGBEE_KEY }}" \
              -e "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" \
              -e "CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}" \
              -e "ANTHROPIC_API_KEY=${{ secrets.CLAUDE_API_KEY }}" \
              -e "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" \
              -e "HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }}" \
              -e "CRAWL4AI_API_TOKEN=${{ secrets.CRAWL4AI_API_TOKEN }}" \
              -e "CRAWL4_AI_BASE_DIRECTORY=/app/data" \
              --restart always \
              --name crawl4ai-container \
              ${{ secrets.DOCKERHUB_USERNAME }}/crawl4ai:latest
            
            # Verify deployment
            sleep 5
            docker ps | grep crawl4ai-container
